name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  phpunit:
    strategy:
      matrix:
        # 测试版本
        php_version: [8.0]
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v2
      # 初始化 PHP 环境
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug
      # 安装 composer 依赖
      - name: Install
        run: composer install
      # 执行 PHPUnit 测试
      - name: PHPUnit
        run: ./vendor/bin/phpunit --coverage-text